spring.application.name=ping

spring.datasource.url= jdbc:postgresql://localhost:5432/ping
spring.datasource.username= pinguser
spring.datasource.password= vinay
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate


jwt.expiry=36000

cookie.expiry=36000

jwt.secret=uiu30924hd203-4023u8204823ii-d9293uie023ihe209e2h9uidjiqw
